# Generated by Django 3.1.4 on 2021-06-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
