# Generated by Django 3.1.4 on 2021-06-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210621_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='blan.png', upload_to=''),
        ),
    ]
